@startuml

title Release Process



package "Git Hub" {
[Repo]
}

package "CI Server" {
[Jenkins] -> [Nexus] : 2. Compile and push binary
}

package "Docker Hub" {
[Registry]
}

package "Docker Machine Server" {
[Docker-Machine]
[Portainer]
}

package "Docker Swarm Servers" {
  package "Docker Swarm 01" {
  [Swarm-Manager]
  }

  package "Docker Swarm 02" {
  [Swarm-Worker]
  }
}
() User --> [Jenkins]
() User --> [Docker-Machine]
[Jenkins] --> Repo : 1. Pull in code
[Jenkins] --> Registry : 3. Build and push image
[Docker-Machine] --> [Swarm-Manager] : 4. Create swarm
[Swarm-Manager] --> [Swarm-Worker]
[Swarm-Manager] --> [Registry] : 5. Pull image
[Swarm-Worker] --> [Registry] : 6. Pull image
[Portainer] --> [Swarm-Manager] : 7. View swarm


@enduml